AWSTemplateFormatVersion: "2010-09-09"
Description: "Securely configured S3 bucket that addresses AWS Security Hub S3.3 control - blocks public write access"

Parameters:
  BucketPrefix:
    Type: String
    Default: "my-secure-bucket"
    Description: "Prefix for the S3 bucket name"

Resources:
  # Securely configured S3 Bucket
  SecureS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketPrefix}-${AWS::StackId}"
      # SECURITY FIX 1: Block Public Access Configuration (addresses S3.3)
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # SECURITY ENHANCEMENT 2: Server-side encryption
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      # SECURITY ENHANCEMENT 3: Versioning enabled
      VersioningConfiguration:
        Status: Enabled
      # SECURITY ENHANCEMENT 4: Access logging
      LoggingConfiguration:
        DestinationBucketName: !Ref SecureS3Bucket
        LogFilePrefix: "access-logs/"
      # SECURITY ENHANCEMENT 5: Lifecycle configuration
      LifecycleConfiguration:
        Rules:
          - Id: "transition-to-ia-and-glacier"
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
            ExpirationInDays: 365
            NoncurrentVersionExpirationInDays: 90
      # Tags for compliance and management
      Tags:
        - Key: "Name"
          Value: "SecureBucket"
        - Key: "Environment"
          Value: "Production"
        - Key: "Purpose"
          Value: "Secure S3 configuration example"
        - Key: "Security"
          Value: "CompliantWithS3.3"
        - Key: "PublicWriteAccess"
          Value: "Blocked"

  # SECURITY FIX 6: Secure bucket policy (account-restricted, no public access)
  SecureBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SecureS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "RestrictedAccountAccess"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
              - "s3:ListBucket"
            Resource:
              - !GetAtt SecureS3Bucket.Arn
              - !Sub "${SecureS3Bucket}/*"
          # Optional: Allow specific roles or users
          # - Sid: "AllowSpecificRole"
          #   Effect: "Allow"
          #   Principal:
          #     AWS: "arn:aws:iam::ACCOUNT-ID:role/ROLE-NAME"
          #   Action:
          #     - "s3:GetObject"
          #     - "s3:ListBucket"
          #   Resource:
          #     - !GetAtt SecureS3Bucket.Arn
          #     - !Sub "${SecureS3Bucket}/*"

Outputs:
  SecureBucketName:
    Description: "Name of the secure S3 bucket"
    Value: !Ref SecureS3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-SecureBucketName"

  SecureBucketArn:
    Description: "ARN of the secure S3 bucket"
    Value: !GetAtt SecureS3Bucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SecureBucketArn"

  SecurityStatus:
    Description: "Security compliance status"
    Value: "✅ SECURE: This bucket blocks public write access and follows AWS security best practices (S3.3 compliant)"

  SecurityControlsImplemented:
    Description: "List of security controls implemented"
    Value: "Block Public Access enabled (S3.3), Private bucket policy, Server-side encryption, Versioning, Access logging, Lifecycle policies"

  ComplianceNote:
    Description: "AWS Security Hub compliance information"
    Value: "This configuration addresses AWS Security Hub control S3.3: S3 general purpose buckets should block public write access"