AWSTemplateFormatVersion: "2010-09-09"
Description: "Secure S3 bucket configuration with proper Block Public Access settings"

Parameters:
  BucketNamePrefix:
    Type: String
    Default: "secure-test-bucket"
    Description: "Prefix for the S3 bucket name"

Resources:
  # Secure S3 Bucket
  SecureS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${BucketNamePrefix}-${AWS::AccountId}-${AWS::Region}"
      # Block all public access to prevent security misconfigurations
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      # Enable versioning for data protection
      VersioningConfiguration:
        Status: Enabled
      # Enable server-side encryption
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      # Configure lifecycle rules
      LifecycleConfiguration:
        Rules:
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      # Add access logging
      LoggingConfiguration:
        DestinationBucketName: !Ref AccessLogBucket
        LogFilePrefix: "access-logs/"
      Tags:
        - Key: "Name"
          Value: "SecureS3Bucket"
        - Key: "Environment"
          Value: "SecurityTesting"
        - Key: "Purpose"
          Value: "Secure configuration for testing"
        - Key: "SecurityStatus"
          Value: "PublicWriteAccessBlocked"

  # Separate bucket for access logs
  AccessLogBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${BucketNamePrefix}-access-logs-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 90

  # CloudWatch Log Group for S3 monitoring (independent resource)
  S3LogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/s3/secure-bucket-${AWS::AccountId}-${AWS::Region}"
      RetentionInDays: 30

Outputs:
  BucketName:
    Description: "Name of the secure S3 bucket"
    Value: !Ref SecureS3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"

  BucketArn:
    Description: "ARN of the secure S3 bucket"
    Value: !GetAtt SecureS3Bucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-BucketArn"

  BucketDomainName:
    Description: "Domain name of the secure S3 bucket"
    Value: !GetAtt SecureS3Bucket.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-BucketDomainName"

  SecurityStatus:
    Description: "Security status of the bucket"
    Value: "✅ SECURE: Public write access is blocked. All Block Public Access settings enabled."
    Export:
      Name: !Sub "${AWS::StackName}-SecurityStatus"

  AccessLogBucket:
    Description: "Name of the access log bucket"
    Value: !Ref AccessLogBucket
    Export:
      Name: !Sub "${AWS::StackName}-AccessLogBucket"