AWSTemplateFormatVersion: "2010-09-09"
Description: "Intentionally misconfigured AWS RDS resources for security misconfiguration demonstration."

Resources:
  MyRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: "misconfig-db-instance"
      Engine: "mysql"
      MasterUsername: "admin"
      MasterUserPassword: "ExamplePassword123!"
      DBInstanceClass: "db.t3.micro"
      AllocatedStorage: 20
      PubliclyAccessible: true  # RDS.2 - Should not be public!
      VPCSecurityGroups:
        - !Ref OpenSecurityGroup
      BackupRetentionPeriod: 0   # No backups
      DeletionProtection: false  # Should be enabled
      StorageEncrypted: false    # Encryption should be enabled

  MyRDSSnapshot:
    Type: AWS::RDS::DBSnapshot
    Properties:
      DBInstanceIdentifier: !Ref MyRDSInstance
      DBSnapshotIdentifier: "misconfig-db-snapshot"
      Tags:
        - Key: "Public"
          Value: "True" # Simulate publicly shared (RDS.1)

  MyAuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora
      MasterUsername: "auroraadmin"
      MasterUserPassword: "AuroraPassword123!"
      DBClusterIdentifier: "misconfig-aurora-cluster"
      BackupRetentionPeriod: 1
      CopyTagsToSnapshot: false # RDS.16 - Should be true!
      StorageEncrypted: false   # Should be true

  OpenSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Open SG for RDS"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0   # Open to the world (bad practice)
